using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ShareholderResearch;
//
//    var stockList = StockList.FromJson(jsonString);

namespace ShareholderResearch.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class StockList
    {
        [JsonProperty("rc")]
        public long Rc { get; set; }

        [JsonProperty("rt")]
        public long Rt { get; set; }

        [JsonProperty("svr")]
        public long Svr { get; set; }

        [JsonProperty("lt")]
        public long Lt { get; set; }

        [JsonProperty("full")]
        public long Full { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("total")]
        public long Total { get; set; }

        [JsonProperty("diff")]
        public List<Diff> Diff { get; set; }
    }

    public partial class Diff
    {
        [JsonProperty("f12")]
        public string F12 { get; set; }

        [JsonProperty("f14")]
        public string F14 { get; set; }
    }

    public partial class StockList
    {
        public static StockList FromJson(string json) => JsonConvert.DeserializeObject<StockList>(json, StockListConverter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this StockList self) => JsonConvert.SerializeObject(self, StockListConverter.Settings);
    }

    internal static class StockListConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}

